version: "3.9"

services:
  db:
    image: "postgres:14.2"
    env_file:
      - .env
    restart: "always"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres-data: {}

networks:
  my-network:
    external: false
